### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yilo2417** [17S051031/document-scanner#1]
File "C:/python/HelloWorld/document-scanner/scan.py", line 48, in <module>
    cnts = sorted(cnts, key = cv2.contourArea, reverse = True)[:10]

error: OpenCV(4.0.0) C:\projects\opencv-python\opencv\modules\imgproc\src\shapedescr.cpp:272: error: (-215:Assertion failed) npoints >= 0 && (depth == CV_32F || depth == CV_32S) in function 'cv::contourArea'

**Comment by lipeng1109** [comment]
> File "C:/python/HelloWorld/document-scanner/scan.py", line 48, in 
> cnts = sorted(cnts, key = cv2.contourArea, reverse = True)[:10]
> 
> error: OpenCV(4.0.0) C:\projects\opencv-python\opencv\modules\imgproc\src\shapedescr.cpp:272: error: (-215:Assertion failed) npoints >= 0 && (depth == CV_32F || depth == CV_32S) in function 'cv::contourArea'

改成这样就可以：
cnts = cnts[1] if imutils.is_cv2() else cnts[0]

**Comment by BaochaoZhu** [comment]
Traceback (most recent call last):
  File "scan.py", line 57, in <module>
    peri = cv2.arcLength(c, True)
cv2.error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\shapedescr.cpp:280: error: (-215:Assertion failed) count >= 0 && (depth == CV_32F || depth == CV_32S) in function 'cv::arcLength'
